# Mnemosys application configuration.

[storage]
path = "/home/charly/Téléchargements"

[profiles]
active_id = "legacy"

[profiles.legacy]
type = "human"
first_name = "Charly"
last_name = "Mercier"
name = ""
team = "Robotic"
view = true
create = true
edit = true
delete = true

[profiles.cf6808da-9313-4e1a-97ec-7fe81e8130cb]
type = "ai"
first_name = ""
last_name = ""
name = "Writer"
team = "Robotic"
view = true
create = false
edit = true
delete = false
